### ISSUE TITLE
Plans to support PHP 8.0?

### ISSUE THREAD

**Issue by LordSimal** [jeromegamez/mite-php#1]
Just checked my application what dependencies do not support PHP 8.0 via composer.json yet and this is one of them.
Are there any plans on trying to update this library to support PHP 8.0 in the near future?

**Comment by jeromegamez** [comment]
Oooh, someone besides me is actually using this 😍. I'll make sure to update the library in the coming days! 🤞

**Comment by LordSimal** [comment]
no stress, just wanted to let you know 😉
and yes, I think your library is awesome 😄

**Comment by LordSimal** [comment]
Just wondering if you had some time working on this issue 😓 
Would love to check if my app works with 8.0

**Comment by jeromegamez** [comment]
@LordSimal Oooh (again 🙈), my apologies, I don't know what came between, but I totally forgot, thank you for reminding me!

Here it is: [Release 1.1](https://github.com/jeromegamez/mite-php/releases/tag/1.1) - let me know if it works for you; if not, I promise I'll react faster 😅

**Comment by jeromegamez** [comment]
And while I'm at it: Here's a [2.0](https://github.com/jeromegamez/mite-php/releases/tag/2.0) 🚀
