### ISSUE TITLE
New mite.de domain name

### ISSUE THREAD

**Issue by LordSimal** [jeromegamez/mite-php#4]
See https://mite.de/api/
and https://mite.de/blog/2023/02/14/anstehender-umzug-auf-mite-de/

**Comment by yolk** [comment]
Shouldn't be an issue. The mite.api still works – and will in the next years – over the old domain schema. We would have broken a lot of API clients otherwise ;-)

**Comment by LordSimal** [comment]
Sure, its just something to keep in mind to update along the way if e.g. a new major version is released.

**Comment by yolk** [comment]
Yepp. I just went ahead and added a pull request: #5

**Comment by jeromegamez** [comment]
Thank you @yolk 🌺 - I just merged #5 with 1631fd97b5cabaec16e813e90e6f41a08cd426d0 🥳 

I'll do some housekeeping (including dropping support for unsupported PHP versions and migrating to GitHub actions) and will create a new major release hopefully today 🤞🏻
